manifest:
  remotes:
    - name: local-repos
      # CRITICAL: This path assumes the student copies 'lab1_start' 
      # to a folder that is peer to 'cache'. 
      # If that's hard to guarantee, use absolute path: 'file:///D:/cache'
      url-base: file:///Users/dantang/zephyr2labs/cache

  projects:
    - name: zephyr
      remote: local-repos
      revision: v4.3.0  # Or a specific tag like v3.5.0
      import: 
        name-allowlist:
          - cmsis
          - mbedtls

    - name: hal_microchip
      remote: local-repos
      revision: main
      path: modules/hal/microchip
      groups:
        - hal

    - name: hal_atmel
      remote: local-repos
      revision: master                          
      path: modules/hal/atmel
      groups:
        - hal

    - name: cmsis
      remote: local-repos
      revision: master
      path: modules/hal/cmsis

    - name: mbedtls
      remote: local-repos
      revision: zephyr_mbedtls_v3.6.5
      path: modules/crypto/mbedtls

  self:
    path: app
